env: prod
net:
  base_url: "https://m1.apifoxmock.com/m1/6957899-6675043-default"
link:
  site: &SITE "https://flutter.cn"
  download: *SITE
text:
  title: "微几"
  subtitle: "见微知著 收于一几"
  copyright: "© 2025 微几科技 · All Rights Reserved"
  user_notice: |
    欢迎使用本软件！在使用前，请注意以下两点：

    ### 1. 🔐 请记住你的密码

    本软件**没有找回密码**的功能。一旦忘记密码，账户将无法恢复，请务必妥善保管！

    ### 2. 🛠️ 密码设置建议

    软件不存储敏感或宝贵数据，因此**无需设置复杂密码**（如特殊符号、长字符等），简单易记即可，方便使用。

    感谢你的理解与支持！😊

maintenance:
  enabled: false
  redirect_url: *SITE
  title: '🛠️ 系统维护公告'
  content: |
    为了提供更好的服务，我们将于 **2025年11月1日 02:00-04:00（北京时间）** 进行系统升级维护。
    
    维护期间，**所有服务将暂时不可用**，请提前保存好您的工作。感谢您的理解与配合！

sections:
  - label: "用户协议"
    type: "url"
    content: *SITE
    group: 1
versions:
  - platform: ""
    channel: ""
    min_version: "1.0.0"
    latest_version: "2.0.0"
    update_url: *SITE
    update_msg: &MSG |
      **发布于 2025年10月29日**

      我们很高兴地宣布，全新版本 **v2.0.0** 正式上线啦！🎉 这次更新带来了令人兴奋的新功能、性能优化和用户体验提升。快来看看都有哪些变化吧！

      ### ✨ 新增功能

      - 🔍 **智能搜索增强**：现在支持模糊匹配和关键词高亮，查找内容更快更准！
      - 📱 **深色模式**：新增系统级深色主题，保护你的眼睛，夜晚使用更舒适🌙。
      - 🧩 **插件系统**：开放插件接口，支持自定义扩展，功能由你做主！
      - 🌐 **多语言支持**：新增简体中文、英文、日文和西班牙语，国际化体验再升级！

      ### 🛠️ 功能优化

      - ⚡ 提升应用启动速度，冷启动时间减少 40%！
      - 🖼️ 优化图片加载逻辑，节省流量，显示更流畅。
      - 🔄 改进同步机制，数据云端同步更稳定可靠。
      - 🎯 重构设置界面，操作更直观，分类更清晰。

      ### 🐞 问题修复

      - 🛑 修复了在特定情况下应用崩溃的问题。
      - 📄 修正文档导出时格式错乱的 Bug。
      - 🔒 修复一处安全漏洞，提升账户安全性。
      - 📱 适配更多安卓/iOS 设备屏幕尺寸。

    force_update_msg: *MSG
